#!/bin/sh
# Apply all saved settings to the live session. Called by bspwmrc and by the settings menu.
. "$HOME/.config/bspwm/scale-env.sh"
FONT_NAME=$(cfg_get FONT Inter)
ICON_THEME=$(cfg_get ICONS Papirus-Dark)
CURSOR_THEME=$(cfg_get CURSOR Adwaita)
printf 'Xft.dpi: %s\nXft.antialias: 1\nXft.hinting: 1\nXft.hintstyle: hintslight\nXft.rgba: rgb\nXcursor.size: %s\nXcursor.theme: %s\n' "$POLYBAR_DPI" "$XCURSOR_SIZE" "$CURSOR_THEME" | xrdb -merge
printf 'configuration { dpi: %s; }\n' "$POLYBAR_DPI" > "$HOME/.config/rofi/dpi.rasi"
cat > "$HOME/.config/rofi/colors.rasi" <<EOF
* {
    base: #1e1e2e; mantle: #181825; s0: #313244; s1: #45475a; text: #cdd6f4; sub: #a6adc8; dim: #6c7086;
    lav: #b4befe; blue: #89b4fa; red: #f38ba8; peach: #fab387; green: #a6e3a1; mauve: #cba6f7;
    accent: $UI_ACCENT;
    background-color: transparent;
    text-color: @text;
}
scrollbar {
    handle-color: @accent;
    handle-width: 6px;
    background-color: @s0;
    border-radius: 8px;
}
EOF
# GTK chrome: font, icon theme and cursor theme are user-configurable; the Catppuccin
# color theme itself is not (that's the desktop's whole identity).
GTK_THEME=catppuccin-mocha-lavender-standard+default
mkdir -p "$HOME/.config/gtk-3.0"
cat > "$HOME/.config/gtk-3.0/settings.ini" <<EOF
[Settings]
gtk-theme-name=$GTK_THEME
gtk-icon-theme-name=$ICON_THEME
gtk-font-name=$FONT_NAME 11
gtk-cursor-theme-name=$CURSOR_THEME
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme=1
gtk-decoration-layout=:close
gtk-enable-animations=1
gtk-overlay-scrolling=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
EOF
cat > "$HOME/.gtkrc-2.0" <<EOF
gtk-theme-name="$GTK_THEME"
gtk-icon-theme-name="$ICON_THEME"
gtk-font-name="$FONT_NAME 11"
EOF
export XCURSOR_THEME="$CURSOR_THEME"
xsetroot -cursor_name left_ptr
bspc config window_gap   "$UI_GAP"
bspc config border_width "$UI_BORDER"
bspc config focused_border_color "$UI_ACCENT"
bspc config presel_feedback_color "$UI_ACCENT"
bspc config automatic_scheme "$(cfg_get SCHEME alternate)"
bspc config split_ratio "$(cfg_get SPLIT 0.5)"
bspc config single_monocle "$(cfg_get SINGLE_MONOCLE false)"
bspc config gapless_monocle "$(cfg_get GAPLESS_MONOCLE false)"
bspc config borderless_monocle "$(cfg_get BORDERLESS_MONOCLE true)"
[ "$(cfg_get FOCUS tap)" = hover ] && bspc config focus_follows_pointer true || bspc config focus_follows_pointer false
bspc config click_to_focus any
# Compositor config: fade animations and shadows are settings (cheap on xrender, no GPU needed)
case "$(cfg_get ANIM subtle)" in
  off)    fading=false; fin=1; fout=1 ;;
  smooth) fading=true; fin=0.025; fout=0.035 ;;
  *)      fading=true; fin=0.05;  fout=0.065 ;;
esac
[ "$(cfg_get SHADOWS off)" = on ] && shadow=true || shadow=false
pc="$HOME/.config/picom/picom.conf"; tmp="$pc.new"
mkdir -p "$HOME/.config/picom"
cat > "$tmp" <<EOF
# Generated by ~/.config/bspwm/apply.sh from settings.conf. Edit settings, not this file.
backend = "xrender";
vsync = false;
# corner-radius stays 0: picom's xrender backend leaves black wedges on opaque
# windows' rounded-off corners instead of revealing what's behind them (only
# the glx backend or picom 12+ handle this correctly). Rofi/polybar/dunst
# still look rounded because they paint their own ARGB shape via cairo.
corner-radius = 0;
use-damage = true;
unredir-if-possible = false;
detect-client-opacity = true;
detect-rounded-corners = true;
log-level = "warn";

fading = $fading;
fade-in-step = $fin;
fade-out-step = $fout;
fade-delta = 8;
no-fading-openclose = false;
fade-exclude = [ "class_g = 'Polybar'", "class_g = 'Dunst'", "class_g = 'gsimplecal'" ];

shadow = $shadow;
shadow-radius = 14;
shadow-opacity = 0.45;
shadow-offset-x = -14;
shadow-offset-y = -10;
shadow-exclude = [ "class_g = 'Polybar'", "class_g = 'Dunst'", "class_g = 'Rofi'", "window_type = 'dock'", "window_type = 'desktop'", "_GTK_FRAME_EXTENTS@:c" ];

wintypes: { dock = { shadow = false; }; tooltip = { fade = true; shadow = false; }; popup_menu = { shadow = false; }; dropdown_menu = { shadow = false; }; };
EOF
if [ "$(cfg_get COMPOSITOR on)" = on ]; then
  if ! cmp -s "$tmp" "$pc" || ! pgrep -x picom >/dev/null; then
    mv "$tmp" "$pc"; pkill -x picom; sleep 0.2
    picom --config "$pc" -b
  else rm -f "$tmp"; fi
else rm -f "$tmp"; pkill -x picom; fi
if pgrep -x dunst >/dev/null; then
  [ "$(cfg_get NOTIFY on)" = on ] && dunstctl set-paused false || dunstctl set-paused true
fi
